# Generated by Django 3.1.3 on 2020-11-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'factor_subjetivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoObjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(choices=[('aereo', 'aereo'), ('carretero', 'carretero'), ('ferreo', 'ferreo'), ('terminales', 'terminales')], default='aereo', max_length=10)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'grupo_objetivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoVariableSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.factorsubjetivo')),
            ],
            options={
                'db_table': 'grupo_variable_subjetivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoVigilado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vigilancia', models.CharField(choices=[('objetivo', 'objetivo'), ('subjetivo', 'subjetivo')], default='objetivo', max_length=9)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'grupo_vigilado',
            },
        ),
        migrations.CreateModel(
            name='TiempoMedida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('origen', models.CharField(choices=[('vigilancia', 'vigilancia'), ('inspeccion', 'inspeccion'), ('control', 'control')], default='VIGILANCIA', max_length=10)),
                ('flag_calculo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tiempo_medida',
            },
        ),
        migrations.CreateModel(
            name='Vigilado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modo', models.CharField(choices=[('aereo', 'aereo'), ('carretero', 'carretero'), ('ferreo', 'ferreo'), ('terminales', 'terminales')], default='aereo', max_length=10)),
                ('nombre', models.CharField(max_length=128)),
                ('ciudad', models.CharField(max_length=64)),
                ('departamento', models.CharField(max_length=64)),
                ('vigilancia', models.CharField(choices=[('integral', 'integral'), ('objetivo', 'objetivo'), ('subjetivo', 'subjetivo')], default='integral', max_length=9)),
                ('nit', models.BigIntegerField()),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovigilado')),
                ('pertenece_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.vigilado')),
            ],
            options={
                'db_table': 'vigilado',
            },
        ),
        migrations.CreateModel(
            name='VariableSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=512)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('rango', models.CharField(blank=True, max_length=512, null=True)),
                ('grupo_variable_subjetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovariablesubjetivo')),
            ],
            options={
                'db_table': 'variable_subjetivo',
            },
        ),
        migrations.CreateModel(
            name='VariableObjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=512)),
                ('descripcion', models.CharField(blank=True, max_length=512, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('rango', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('c', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('s', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('a', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('imp_c', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('imp_s', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('imp_a', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupoobjetivo')),
            ],
            options={
                'db_table': 'variable_objetivo',
            },
        ),
        migrations.CreateModel(
            name='MedidaSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('fuerte', 'fuerte'), ('avanzado', 'avanzado'), ('intermedio', 'intermedio'), ('debil', 'debil'), ('inadecuado', 'inadecuado'), ('no existe', 'no existe')], default='no existe', max_length=10)),
                ('valor', models.IntegerField()),
                ('tiempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.tiempomedida')),
                ('variable_subjetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.variablesubjetivo')),
                ('vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.vigilado')),
            ],
            options={
                'db_table': 'medida_subjetivo',
            },
        ),
        migrations.CreateModel(
            name='MedidaObjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=24)),
                ('valor', models.IntegerField()),
                ('ingresado', models.CharField(blank=True, max_length=24, null=True)),
                ('evaluado', models.CharField(blank=True, max_length=24, null=True)),
                ('tiempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.tiempomedida')),
                ('variable_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.variableobjetivo')),
                ('vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.vigilado')),
            ],
            options={
                'db_table': 'medida_objetivo',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('estrategico', 'estrategico'), ('tactico', 'tactico'), ('subjetivo', 'subjetivo'), ('factor', 'factor')], default='tactico', max_length=13)),
                ('nombre', models.CharField(max_length=128)),
                ('valor', models.FloatField()),
                ('tiempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.tiempomedida')),
                ('vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.vigilado')),
            ],
            options={
                'db_table': 'indicador',
            },
        ),
        migrations.CreateModel(
            name='GrupoVigiladoVigilado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grupo_vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovigilado')),
                ('vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.vigilado')),
            ],
            options={
                'db_table': 'grupo_vigilado_vigilado',
            },
        ),
        migrations.CreateModel(
            name='GrupoVigiladoVariableSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obligatoria', models.CharField(choices=[('S', 'S'), ('N', 'N')], default='N', max_length=1)),
                ('grupo_vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovigilado')),
                ('variable_subjetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.variablesubjetivo')),
            ],
            options={
                'db_table': 'grupo_vigilado_variable_subjetivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoVigiladoVariableObjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grupo_vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovigilado')),
                ('variable_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.variableobjetivo')),
            ],
            options={
                'db_table': 'grupo_vigilado_variable_objetivo',
            },
        ),
        migrations.CreateModel(
            name='GrupoVigiladoFactorSubjetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ponderacion', models.IntegerField(blank=True, null=True)),
                ('factor_subjetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.factorsubjetivo')),
                ('grupo_vigilado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='metodologia.grupovigilado')),
            ],
            options={
                'db_table': 'grupo_vigilado_factor_subjetivo',
            },
        ),
    ]
