# Generated by Django 3.1.3 on 2020-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodologia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('estrategico', 'estrategico'), ('tactico', 'tactico'), ('subjetivo', 'subjetivo'), ('factor general', 'factor general'), ('factor obligatorio', 'factor obligatorio'), ('factor riesgo', 'factor riesgo')], default='tactico', max_length=20),
        ),
    ]
